"use client";
import { useState } from "react";
import Markdown from "@/components/Markdown";

export default function IncidentReport() {
  const [loading, setLoading] = useState(false);
  const [markdown, setMarkdown] = useState("");
  const [error, setError] = useState("");

  const generate = async () => {
    setLoading(true);
    setMarkdown("");
    setError("");
    try {
      const res = await fetch("/api/report", { method: "POST" });
      const data = await res.json();
      if (data.error) setError(data.error);
      else setMarkdown(data.markdown);
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  const download = () => {
    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `sentinelai-report-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-gray-900 rounded-xl border border-gray-700 p-4 mt-4">
      <div className="flex items-center justify-between mb-3">
        <h2 className="text-white font-semibold text-sm uppercase tracking-widest">
          ⎈ Incident Report
        </h2>
        <div className="flex gap-2">
          {markdown && (
            <button
              onClick={download}
              className="text-xs bg-gray-800 hover:bg-gray-700 text-gray-200 px-3 py-1.5 rounded-md border border-gray-700"
            >
              Download .md
            </button>
          )}
          <button
            onClick={generate}
            disabled={loading}
            className="text-xs bg-emerald-600 hover:bg-emerald-700 text-white px-3 py-1.5 rounded-md disabled:opacity-50"
          >
            {loading ? "Generating…" : "Generate Report"}
          </button>
        </div>
      </div>

      {error && <p className="text-red-400 text-xs">{error}</p>}

      {markdown && (
        <div className="bg-gray-950 border border-gray-800 rounded-lg p-4 max-h-128 overflow-y-auto">
          <Markdown>{markdown}</Markdown>
        </div>
      )}

      {!markdown && !error && !loading && (
        <p className="text-gray-500 text-xs">
          One-click after-action report generated by Groq from live breach data.
        </p>
      )}
    </div>
  );
}
